import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";
import animate from "tailwindcss-animate";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    screens: {
      xs: "475px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      fontFamily: {
        // Display family for route headers and premium navigation surfaces.
        // Shares the sans fallback stack so platforms without Plus Jakarta Sans
        // (typical on Windows/Linux) degrade to the same body fallbacks.
        display: [
          "Plus Jakarta Sans",
          "DM Sans",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        sans: [
          "Plus Jakarta Sans",
          "DM Sans",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SF Mono",
          "Menlo",
          "Monaco",
          "Cascadia Mono",
          "Segoe UI Mono",
          "Roboto Mono",
          "Oxygen Mono",
          "Ubuntu Mono",
          "DejaVu Sans Mono",
          "Liberation Mono",
          "Source Code Pro",
          "Fira Mono",
          "Consolas",
          "Courier New",
          "monospace",
        ],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          secondary: "#0EA5E9",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        surface: {
          canvas: "hsl(var(--surface-canvas))",
          panel: "hsl(var(--surface-panel))",
          raised: "hsl(var(--surface-raised))",
          inset: "hsl(var(--surface-inset))",
          muted: "hsl(var(--surface-muted))",
        },
        line: {
          subtle: "hsl(var(--border-subtle))",
          DEFAULT: "hsl(var(--border-default))",
          strong: "hsl(var(--border-strong))",
        },
        state: {
          hover: "hsl(var(--state-hover))",
          selected: "hsl(var(--state-selected))",
          "selected-foreground": "hsl(var(--state-selected-foreground))",
          "selected-border": "hsl(var(--state-selected-border))",
        },
        brand: {
          DEFAULT: "#2563EB",
          secondary: "#0EA5E9",
        },
        success: { DEFAULT: "#34D399" },
        warning: { DEFAULT: "#FB923C" },
        danger: { DEFAULT: "#F87171" },
        info: { DEFAULT: "#0EA5E9" },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        heatmap: {
          0: "var(--heatmap-l0)",
          1: "var(--heatmap-l1)",
          2: "var(--heatmap-l2)",
          3: "var(--heatmap-l3)",
          4: "var(--heatmap-l4)",
        },
        page: {
          accent: "hsl(var(--page-accent-color))",
          secondary: "hsl(var(--page-secondary-color))",
        },
        "theme-option": {
          light: "hsl(var(--theme-option-light))",
          dark: "hsl(var(--theme-option-dark))",
          system: "hsl(var(--theme-option-system))",
        },
        glass: {
          DEFAULT: "hsl(var(--glass-surface))",
          border: "hsl(var(--glass-border))",
        },
        trace: {
          "live-from": "hsl(var(--trace-live-from))",
          "live-to": "hsl(var(--trace-live-to))",
          "metric-surface": "hsl(var(--trace-metric-surface))",
          "metric-border": "hsl(var(--trace-metric-border))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          panel: "hsl(var(--sidebar-panel))",
          muted: "hsl(var(--sidebar-muted))",
          control: "hsl(var(--sidebar-control))",
          "control-border": "hsl(var(--sidebar-control-border))",
          "control-muted": "hsl(var(--sidebar-control-muted))",
          "control-inset": "hsl(var(--sidebar-control-inset))",
          "option-active": "hsl(var(--sidebar-option-active))",
        },
        // Legacy bridge (deprecated — migrate to shadcn tokens above)
        bg: {
          primary: "var(--color-bg-primary)",
          secondary: "var(--color-bg-secondary)",
          card: "var(--color-bg-card)",
        },
        "text-theme": {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
        },
        "border-theme": {
          DEFAULT: "var(--color-border)",
          light: "var(--color-border-light)",
        },
      },
      spacing: {
        "4.5": "1.125rem",
      },
      borderRadius: {
        "3xl": "calc(var(--radius) + 8px)",
        "2xl": "calc(var(--radius) + 4px)",
        xl: "calc(var(--radius) + 2px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        card: "none",
        elevated: "var(--shadow-elevated)",
        panel: "var(--shadow-panel)",
        dialog: "var(--shadow-dialog)",
        "heatmap-strong": "var(--heatmap-l4-glow)",
        "page-accent-soft": "var(--shadow-page-accent-soft)",
        "sidebar-control": "var(--shadow-sidebar-control)",
        "sidebar-control-hover": "var(--shadow-sidebar-control-hover)",
        "sidebar-option": "var(--shadow-sidebar-option)",
        "trace-metric": "var(--shadow-trace-metric)",
        "trace-card": "var(--shadow-trace-card)",
        "trace-card-hover": "var(--shadow-trace-card-hover)",
        "trace-panel-hover": "var(--shadow-trace-panel-hover)",
        "trace-panel-live-hover": "var(--shadow-trace-panel-live-hover)",
        "pill-subtle": "var(--shadow-pill-subtle)",
        "status-dot": "0 0 8px var(--tw-shadow-color)",
        "status-dot-sm": "0 0 5px var(--tw-shadow-color)",
        "request-log-selected": "var(--shadow-request-log-selected)",
        "request-log-hover": "var(--shadow-request-log-hover)",
        "request-log-hover-dark": "var(--shadow-request-log-hover-dark)",
      },
      dropShadow: {
        "page-accent": "var(--drop-shadow-page-accent)",
      },
      transitionDuration: {
        400: "400ms",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [typography, animate],
} satisfies Config;
