export const USAGE_DEFAULT_FULL_IDLE_GAP_MINUTES = 15;
export const USAGE_DEFAULT_SESSION_BREAK_GAP_MINUTES = 30;
export const USAGE_FULL_IDLE_GAP_MINUTES_MIN = 1;
export const USAGE_FULL_IDLE_GAP_MINUTES_MAX = 30;
export const USAGE_SESSION_BREAK_GAP_MINUTES_MIN = 15;
export const USAGE_SESSION_BREAK_GAP_MINUTES_MAX = 60;
